### ISSUE TITLE
can't execute dedicated_launcher

### ISSUE THREAD

**Issue by Toni500github** [nillerusr/source-engine#268]
so i have built the engine with `./waf configure -T release --64bits -d --prefix "/home/toni/.local/share/Steam/steamapps/common/Half-Life 2/"` then run `./waf install` and installed the libraries to the prefix folder. everytime i try to launch `dedicated_launcher` it says `Failed to open bin/dedicated.so (libvstdlib.so: cannot open shared object file: No such file or directory)` even tho the libvstdlib.so files it's in the bin/ folder

**Comment by stephen-cusi** [comment]
> 所以我已经构建了引擎，`./waf configure -T release --64bits -d --prefix "/home/toni/.local/share/Steam/steamapps/common/Half-Life 2/"`然后运行`./waf install`并将库安装到前缀文件夹中。每次我尝试启动它时`dedicated_launcher`，它甚至说`Failed to open bin/dedicated.so (libvstdlib.so: cannot open shared object file: No such file or directory)`libvstdlib.so 文件在 bin/ 文件夹中



> 所以我已经构建了引擎，`./waf configure -T release --64bits -d --prefix "/home/toni/.local/share/Steam/steamapps/common/Half-Life 2/"`然后运行`./waf install`并将库安装到前缀文件夹中。每次我尝试启动它时`dedicated_launcher`，它甚至说`Failed to open bin/dedicated.so (libvstdlib.so: cannot open shared object file: No such file or directory)`libvstdlib.so 文件在 bin/ 文件夹中



> so i have built the engine with `./waf configure -T release --64bits -d --prefix "/home/toni/.local/share/Steam/steamapps/common/Half-Life 2/"` then run `./waf install` and installed the libraries to the prefix folder. everytime i try to launch `dedicated_launcher` it says `Failed to open bin/dedicated.so (libvstdlib.so: cannot open shared object file: No such file or directory)` even tho the libvstdlib.so files it's in the bin/ folder
export LD_LIBRARY_PATH

**Comment by stephen-cusi** [comment]
> 

The following is the answer given by GPT 4, hoping to be useful to you
`It seems like the problem is related to not being able to find the shared libraries at runtime. You can try the following solutions:

1. Set the environment variable `LD_LIBRARY_PATH` to include the path to the `bin/` directory that contains the missing libraries:

   ```
   export LD_LIBRARY_PATH="/home/toni/.local/share/Steam/steamapps/common/Half-Life 2/bin/:$LD_LIBRARY_PATH"
   ```

   After setting the variable, try running the `dedicated_launcher` again.

2. Alternatively, you can use the `ldconfig` utility to permanently include the path to the shared libraries. To do this, follow the steps below:

   a. Create or edit the file `/etc/ld.so.conf.d/half-life2.conf` using a text editor with root privileges. For example:

      ```
      sudo nano /etc/ld.so.conf.d/half-life2.conf
      ```

   b. Add the following line to the file:

      ```
      /home/toni/.local/share/Steam/steamapps/common/Half-Life 2/bin/
      ```

   c. Save and close the file.

   d. Run `sudo ldconfig` to update the library cache.

   e. Now try running the `dedicated_launcher` again.

If neither of these solutions works, ensure that the `libvstdlib.so` file is the correct version for your system (64-bit or 32-bit) and that it is not corrupted. You may want to verify the `libvstdlib.so` dependencies using the `ldd` command:

```
ldd /home/toni/.local/share/Steam/steamapps/common/Half-Life 2/bin/libvstdlib.so
```

If there are any missing dependencies, ensure they are installed and available on your system.`

**Comment by Toni500github** [comment]
ye i worked at the 1st solution. thanks
