### ISSUE TITLE
Opengl/gallium nine /wayland

### ISSUE THREAD

**Issue by neofeo** [nillerusr/source-engine#393]
Hi sir! Very good job here. I've noted that the engine still uses the built-in dx9 to gl wrapper, would be possible to use clean opengl or gallium nine down the road? The built-in wrapper isn't that great.

Also, it doesn't work with sdl wayland neither.

BR, salva

**Comment by hangocdinhnew** [comment]
> Hi sir! Very good job here. I've noted that the engine still uses the built-in dx9 to gl wrapper, would be possible to use clean opengl or gallium nine down the road? The built-in wrapper isn't that great.
> 
> Also, it doesn't work with sdl wayland neither.
> 
> BR, salva

Hello, there, I have a comment regarding this:

First off, this repo uses togl which is a hacky way by Valve to translate from DX9 to OpenGL, using pure OpenGL would limit the capability to expand to Vulkan as, Vulkan is pretty much on the plan, and there's no existing "OpenGL to Vulkan" translation layer, as Vulkan requires very complex code, when rendering a cube, it can took a bunch of effort, as it requires swapchains, and etc, OpenGL doesn't care about these, so it's very easy, but that lacks the control of Vulkan, and we're seeing progress to even implement DXVK into Half-Life 2 (The build from Steam), for cross-platform compatibility, as for OpenGL, well, OpenGL is certainly aging but it still survives, and it's easy, so we surely would keep OpenGL in the near future, and make Vulkan as default, but it would take a lot of progress.

As for the Gallium 9, it will take a lot of effort to do Gallium 9, because Gallium 9 is Linux only, sure we can do that but in the future, essentially we're maintaining 3 graphics wrapper, and Gallium 9 is primarly used in with Wine, so, it's not very ideal to do this.

And as a quick reminder, this is just my opinion in the form of comments.

**Comment by mittorn** [comment]
There is xnine wrapper for dxvk-enabled source games. So it's should be possible to support both dxvk and gallium-nine with same code
